name: GC Build - QA

on:
  push:
    branches: [ "docker-build" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: maven-build
      run: mvn package -Dmaven.test.skip.exec -Dmaven.test.skip=true

    - name: Build Docker image
      id: docker-build
      run: docker build -t ${{ secrets.ECR_URL}}/${{secrets.ECR_REPOSITORY}}:latest .

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  

    - name: Push docker image to ECR
      run: docker push ${{ secrets.ECR_URL}}/${{secrets.ECR_REPOSITORY}}:latest