name: GC Build - QA

on:
  push:
    branches: [ "docker-build" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: maven-build
      run: mvn package -Dmaven.test.skip.exec -Dmaven.test.skip=true